trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    python-version: ['3.9', '3.10', '3.11']

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python-version)'
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'
- script: |
    pytest
  displayName: 'Run tests'
