# .azure-pipelines.yml

trigger:
- main  # Branches that trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'  # Agent pool to use

variables:
  pythonVersion: '3.10'  # Specify the Python version

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(pythonVersion)
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pytest --maxfail=1 --disable-warnings -q
  displayName: 'Run tests'

- script: |
    python -m build
  displayName: 'Build package'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/dist'
    artifactName: 'drop'
  displayName: 'Publish artifact'
