---
name: NeuroFlex CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create necessary directories
        run: |
          mkdir -p ${{ github.workspace }}/data
          mkdir -p ${{ github.workspace }}/path/to/save
      - name: Set ALPHAFOLD_PATH environment variable
        run: echo "ALPHAFOLD_PATH=${{ github.workspace }}/alphafold" >> $GITHUB_ENV
      - name: Run tests
        run: |
          pytest tests/ --disable-warnings
        env:
          NEUROFLEX_DATA_DIR: ${{ github.workspace }}/data
          NEUROFLEX_SAVE_DIR: ${{ github.workspace }}/path/to/save
          ALPHAFOLD_PATH: ${{ env.ALPHAFOLD_PATH }}
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build package
        run: |
          pip install build
          python -m build
