name: Python 3.11

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Python 3.11
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Clear pip cache and install dependencies
      run: |
        python -m pip cache purge
        python -m pip install --upgrade pip
        pip install -r requirements.txt --no-cache-dir
    - name: Run tests
      run: |
        pytest tests/
